backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "public/assets/img"
public_folder: "/assets/img"

collections:
  - name: "galery"
    label: "Galerie"
    folder: "src/galery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Auteur", name: "author", widget: "string" }
      - {
          label: "Catégorie",
          name: "categorie",
          widget: select,
          options:
            [
              "Mariage",
              "Famille",
              "Couple",
              "Grossesse",
              "Bebe",
              "Bapteme",
              "Portrait",
            ],
        }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description de l'image", name: "imageAlt", widget: "string" }
